internalName: mrj_keyboard

locales:
  en:
    name: &bundleName "Western Mari Keyboards"
    description: "Mobile OS keyboards for the Western Mari language from the Divvun group at UiT."
  nb:
    name: "Western Mari tastatur"
    description: "Mobiltastatur for Western Mari fra Divvun-gruppa."

author: The Divvun Group, UiT Norgga 치rktala코 universitehta
email: feedback@divvun.no

copyright: (c) 2017 Divvun/Giellatekno/UiT
organisation: UiT Norgga 치rktala코 universitehta

layouts: [mrj]

version: 1.0
build: 1

targets:
  android:
    packageId: no.uit.giella.keyboards.__UND__
    icon: images/__UND__-icon.pdf
    keyStore: /Users/brendan/git/softkbdgen/test.keystore
    keyAlias: mrj_keyboard

  ios: &AppleID
    codeSignId: "iOS Development"
    provisioningProfileId: Test
    packageId: no.uit.giella.keyboards.mrj
    bundleName: *bundleName
    icon: images/__UND__-icon.png
  osx: *AppleID
