internalName: mrj_ru-win

locales:
  en:
    name: &bundleName "Western Mari Keyboards"
    description: "Mobile OS keyboards for the Western Mari language from the Divvun group at UiT."
  nb:
    name: "Western Mari tastatur"
    description: "Mobiltastatur for Western Mari fra Divvun-gruppa."

author: The Divvun Group, UiT Norgga 치rktala코 universitehta
email: feedback@divvun.no

copyright: (c) 2017 Divvun/Giellatekno/UiT
organisation: UiT Norgga 치rktala코 universitehta

layouts: [mrj-mob, mrj-mac, mrj-win]

version: 1.0
build: 1

targets:
  android:
    packageId: no.uit.giella.keyboards.mrj
    icon: images/mrj-icon.pdf
    keyStore: $GTPRIV/admin/dev-accounts/dev_keys/sami_keyboard.keystore
    keyAlias: sami_keyboard
    version: "1.0.0"
    build: "1"

  ios: &AppleID
    codeSignId: "2K5J2584NX"
    provisioningProfileId: Test
    packageId: no.uit.giella.keyboards.mrj
    bundleName: *bundleName
    icon: images/mrj-icon.png
    version: "1.0.0"
    build: "1"

  osx:
    <<: *AppleID
    icon: images/mrj-keyboard-menu-icon.png
    version: 0.1.0
    resources: doc
    version: "1.0.0"
    build: "1"

  win:
    appName: *bundleName
    version: 0.1.0
    url: "http://divvun.no"
    uuid: "31B7E218-9339-4A51-A2F2-396BB13D9991"
    version: "1.0.0"
    build: "1"
